name: Compile

on:

  workflow_dispatch:
    inputs:
      repository:
        required: true
        default: 'immortalwrt/immortalwrt'
        type: string
        description: '作者/仓库'
      branch:
        required: true
        default: 'master'
        type: string
        description: '分支'

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        root-reserve-mb: '6789'

    - name: Initialization Environment
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

    - name: Checkout
      uses: actions/checkout@main

    - name: Checkout ImmortalWrt
      uses: actions/checkout@main
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        path: Router

    - name: Feeds And Config
      run: |
        cd Router
        scripts/feeds update -a
        scripts/feeds install -a
        mv ../.config .
        make defconfig

    - name: Compile The Firmware
      run: |
        cd Router
        make -j$[`nproc`+1] || make -j$(nproc) || make -j1 V=sc
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "RELEASE=$(date)" >> $GITHUB_ENV

    - name: Git Push To Branch
      run: |
        cd Router/bin
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b ${{ env.DEVICE_NAME }}
        git add .
        git commit -m "${{ env.RELEASE }}"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin ${{ env.DEVICE_NAME }}

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        keep_minimum_runs: 0
        retain_days: 0
