#
# Copyright (c) 2019-2023 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: Package Update Checker

env:
  REPO_URL: https://github.com/immortalwrt/packages
  REPO_BRANCH: openwrt-21.02

on:
  workflow_dispatch:
  schedule:
    - cron: '1 23 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --depth 1 --single-branch .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@main
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo "FILE_DATE=$(date +"%Y.%m.%d_%H:%M")" >> $GITHUB_ENV

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@main
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Package_${{ env.FILE_DATE }}
